import httpx
import pytest

from app.core.exceptions import TranscriptUnavailableError
from app.providers.caption_formats import parse_ttml, parse_webvtt
from app.providers.caption_mirror import CaptionMirrorTranscriptProvider


def test_parse_webvtt_timestamps() -> None:
    cues = parse_webvtt(
        """WEBVTT

00:00:43.120 --> 00:00:45.840
Never gonna give you up

00:01:02.000 --> 00:01:04.500
Feldman Automotive
"""
    )
    assert cues[0].start == 43.12
    assert cues[0].duration == pytest.approx(2.72)
    assert cues[0].text == "Never gonna give you up"
    assert cues[1].start == 62.0
    assert cues[1].text == "Feldman Automotive"


def test_parse_ttml_paragraphs() -> None:
    cues = parse_ttml(
        """<?xml version="1.0" encoding="utf-8" ?>
<tt xmlns="http://www.w3.org/ns/ttml">
<body>
<p begin="00:00:18.800" end="00:00:21.800">We're no strangers to</p>
</body>
</tt>
"""
    )
    assert len(cues) == 1
    assert cues[0].start == 18.8
    assert cues[0].duration == pytest.approx(3.0)
    assert "strangers" in cues[0].text


def test_caption_mirror_uses_invidious_vtt() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path.endswith("/captions/dQw4w9WgXcQ") and not request.url.query:
            return httpx.Response(
                200,
                json={
                    "captions": [
                        {"label": "English (auto-generated)", "languageCode": "en", "url": "/api/v1/captions/dQw4w9WgXcQ?label=English%20(auto-generated)"}
                    ]
                },
            )
        if "label=" in str(request.url):
            return httpx.Response(
                200,
                text="WEBVTT\n\n00:00:43.000 --> 00:00:45.000\nNever gonna give you up\n",
            )
        return httpx.Response(404, text="missing")

    client = httpx.Client(transport=httpx.MockTransport(handler))
    cues = CaptionMirrorTranscriptProvider(
        client=client,
        invidious_bases=["https://inv.example.test"],
        piped_bases=[],
    ).fetch("dQw4w9WgXcQ")
    assert cues[0].text == "Never gonna give you up"
    assert cues[0].start == 43.0


def test_caption_mirror_falls_back_to_piped_json3() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        if "/api/v1/captions/" in str(request.url):
            return httpx.Response(503, text="down")
        if request.url.path.endswith("/streams/dQw4w9WgXcQ"):
            return httpx.Response(
                200,
                json={
                    "subtitles": [
                        {
                            "code": "en",
                            "name": "English",
                            "autoGenerated": True,
                            "url": "https://proxy.example.test/api/timedtext?fmt=ttml&lang=en",
                        }
                    ]
                },
            )
        if "fmt=json3" in str(request.url):
            return httpx.Response(
                200,
                json={"events": [{"tStartMs": 1000, "dDurationMs": 2000, "segs": [{"utf8": "From Piped"}]}]},
            )
        return httpx.Response(404, text="missing")

    client = httpx.Client(transport=httpx.MockTransport(handler))
    cues = CaptionMirrorTranscriptProvider(
        client=client,
        invidious_bases=["https://inv.example.test"],
        piped_bases=["https://piped.example.test"],
    ).fetch("dQw4w9WgXcQ")
    assert cues[0].text == "From Piped"
    assert cues[0].start == 1.0


def test_caption_mirror_unavailable_when_all_hosts_fail() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(503, text="down")

    client = httpx.Client(transport=httpx.MockTransport(handler))
    with pytest.raises(TranscriptUnavailableError):
        CaptionMirrorTranscriptProvider(
            client=client,
            invidious_bases=["https://inv.example.test"],
            piped_bases=["https://piped.example.test"],
        ).fetch("dQw4w9WgXcQ")


def test_caption_mirror_skips_piped_bot_check_json() -> None:
    def handler(request: httpx.Request) -> httpx.Response:
        if "/api/v1/captions/" in str(request.url):
            return httpx.Response(503, text="down")
        return httpx.Response(
            200,
            json={
                "error": "org.schabi.newpipe.extractor.exceptions.SignInConfirmNotBotException: blocked",
                "message": 'YouTube probably temporarily blocked anonymous watch access with this IP , got error LOGIN_REQUIRED: "Sign in to confirm that you\'re not a bot"',
            },
        )

    client = httpx.Client(transport=httpx.MockTransport(handler))
    with pytest.raises(TranscriptUnavailableError, match="bot-check") as exc_info:
        CaptionMirrorTranscriptProvider(
            client=client,
            invidious_bases=["https://inv.example.test"],
            piped_bases=["https://piped.example.test"],
        ).fetch("dQw4w9WgXcQ")
    assert "org.schabi" not in str(exc_info.value)
    assert "at org." not in str(exc_info.value)
